# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

inherit java-pkg

DESCRIPTION="Java plugin for Maven"
HOMEPAGE="http://maven.apache.org"
# svn co http://svn.apache.org/repos/asf/maven/maven-1/plugins/tags/MAVEN_JAVA_1_5/ maven-java-plugin-1.5
# tar cjvf maven-java-plugin-1.5-gentoo.tar.bz2 maven-java-plugin-1.5
SRC_URI="http://gentooexperimental.org/distfiles/${P}-gentoo.tar.bz2"

LICENSE="Apache-2.0"
SLOT="1"
KEYWORDS="~x86"
IUSE=""

RDEPEND=">=virtual/jre-1.4
	dev-java/ant-core"
DEPEND="${RDEPEND}"

S="${WORKDIR}/${P}/java"

src_unpack() {
	unpack ${A}

	cd ${S}
	# This build.xml was generated by 'maven ant', and fixed slightly.
	cp ${FILESDIR}/build-${PV}.xml build.xml
}

src_compile() {
	local antflags="jar -Dnoget=true"
	ant ${antflags} || die "ant failed"
}

src_install() {
	java-pkg_newjar target/${P}.jar ${PN}.jar
}
