# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

inherit java-maven java-pkg

DESCRIPTION="Xdoc plugin for Maven"
HOMEPAGE="http://maven.apache.org"
# svn co http://svn.apache.org/repos/asf/maven/maven-1/plugins/tags/MAVEN_XDOC_1_8/xdoc/ maven-xdoc-plugin-1.8
# tar cjvf maven-xdoc-plugin-1.8-gentoo.tar.bz2 maven-xdoc-plugin-1.8/
SRC_URI="http://gentooexperimental.org/distfiles/${P}-gentoo.tar.bz2"

LICENSE="Apache-2.0"
SLOT="1"
KEYWORDS="~x86"
IUSE=""

RDEPEND=">=virtual/jdk-1.4
	=dev-java/dom4j-1*
	=dev-java/commons-jelly-1*
	=dev-java/commons-jelly-tags-jsl-1*
	=dev-java/commons-jelly-tags-log-1*
	=dev-java/commons-jelly-tags-velocity-1*
	=dev-java/commons-jelly-tags-xml-1*
	dev-java/commons-logging
	=dev-java/maven-core-1*
	dev-java/velocity
	dev-java/dvsl
	dev-java/xml-commons"
DEPEND="${RDEPEND}"

src_unpack() {
	unpack ${A}

	cd ${S}
	# This build.xml was generated by 'maven ant', and fixed slightly.
	cp ${FILESDIR}/build-${PV}.xml build.xml

	mkdir -p target/lib
	cd target/lib
	java-pkg_jar-from dom4j-1
	java-pkg_jar-from commons-jelly-1
	java-pkg_jar-from commons-jelly-tags-jsl-1
	java-pkg_jar-from commons-jelly-tags-log-1
	java-pkg_jar-from commons-jelly-tags-velocity-1
	java-pkg_jar-from commons-jelly-tags-xml-1
	java-pkg_jar-from commons-logging
	java-pkg_jar-from maven-core-1
	java-pkg_jar-from velocity
	java-pkg_jar-from dvsl
	java-pkg_jar-from xml-commons xml-apis.jar
}

src_compile() {
	local antflags="jar -Dnoget=true"
	ant ${antflags} || die "ant failed"
}

src_install() {
	java-maven_newplugin target/${P}.jar ${PN}.jar
}
