# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

JAVA_MAVEN_BOOTSTRAP="Y"
inherit java-maven-2

DESCRIPTION="Maven is a software project management and comprehension tool."
HOMEPAGE="http://maven.apache.org/"
MY_BASE_URL="http://dev.gentooexperimental.org/~kiorky"
SRC_URI="${MY_BASE_URL}/${P}.tar.bz2
${MY_BASE_URL}/${P}-gen-src.tar.bz2"
LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~x86"
IUSE="source doc"
COMMON_DEPS="
>=dev-java/plexus-container-default-1.0_alpha33_pre20071021
>=dev-java/plexus-utils-1.4.7_pre20071021
=dev-java/jakarta-oro-2.0*
dev-java/junit
dev-java/plexus-i18n
dev-java/velocity
=dev-java/itext-1.4
dev-java/plexus-velocity"
DEPEND=">=virtual/jdk-1.4 ${COMMON_DEPS}"
RDEPEND=">=virtual/jre-1.4 ${COMMON_DEPS}"

JAVA_MAVEN_CLASSPATH="
plexus-container-default-1.0_alpha33
plexus-utils-1.4.7
jakarta-oro-2.0
junit
itext-1.4
plexus-i18n
plexus-velocity
velocity
"
# PLEASE KEEP  THE ORDER !
JAVA_MAVEN_PROJECTS="
doxia-sink-api
doxia-core
doxia-modules/doxia-module-confluence
doxia-modules/doxia-module-docbook-simple
doxia-modules/doxia-module-twiki
doxia-modules/doxia-module-xdoc
doxia-modules/doxia-module-apt
doxia-modules/doxia-module-itext
doxia-modules/doxia-module-fml
doxia-modules/doxia-module-latex
doxia-modules/doxia-module-rtf
doxia-modules/doxia-module-xhtml
doxia-modules
"

src_unpack(){
	java-maven-2_src_unpack
	# add java/plexus sources generated by a maven plugin
	cd "${S}" || die
	unpack "${P}-gen-src.tar.bz2"
}
