# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

inherit java-maven

DESCRIPTION="Clean plugin for Maven"
HOMEPAGE="http://maven.apache.org"
# svn co http://svn.apache.org/repos/asf/maven/maven-1/plugins/tags/MAVEN_CLEAN_1_3/clean maven-clean-plugin-1.3
# tar cjvf maven-clean-plugin-1.3-gentoo.tar.bz2 maven-clean-plugin-1.3
SRC_URI="http://gentooexperimental.org/distfiles/${P}-gentoo.tar.bz2"


LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~x86"
IUSE=""

DEPEND=">=virtual/jdk-1.4
	dev-java/ant-core"
RDEPEND="${DEPEND}"

src_unpack() {
	unpack ${A}

	cd ${S}
	# This build.xml was generated by 'maven ant', and fixed slightly.
	cp ${FILESDIR}/build-${PV}.xml build.xml
}

src_compile() {
	local antflags="jar -Dnoget=true"
	ant ${antflags} || die "ant failed"
}

src_install() {
	java-maven_newplugin target/${P}.jar ${PN}.jar
}
