# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

inherit eutils java-pkg-2

DESCRIPTION=" FreeMarker is a template engine; a generic tool to generate text output (anything from HTML to autogenerated source code) based on templates."
HOMEPAGE="http://freemarker.sourceforge.net/"
SRC_URI="mirror://sourceforge/${PN}/${P}.tar.gz"

LICENSE="freemarker"
SLOT="2.3"
KEYWORDS="~amd64 ~x86"
IUSE="doc"

DEPEND=">=virtual/jdk-1.4
	dev-java/ant-core"
RDEPEND=">=virtual/jre-1.4
	=dev-java/servletapi-2.3*
	=dev-java/jaxen-1.1*
	dev-java/javacc"

GETJARS_ARG="servletapi-2.3,jaxen-1.1"

src_unpack() {

	unpack ${A}
	epatch "${FILESDIR}/${P}-gentoo.patch"

}

src_compile() {

	local antflags="jar -Djavacc.home=/usr/share/javacc/lib -lib $(java-pkg_getjars ${GETJARS_ARG})"

	use doc && antflags="${antflags} javadoc"

	eant clean ${antflags} || die "Compilation failed"

}

src_install() {

	java-pkg_dojar lib/${PN}.jar
	dodoc README.txt

	use doc && java-pkg_dohtml -r build/api

}
