# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

inherit java-maven java-pkg

DESCRIPTION="License plugin for Maven"
HOMEPAGE="http://maven.apache.org"
#  svn co http://svn.apache.org/repos/asf/maven/maven-1/plugins/tags/MAVEN_LICENSE_1_2 maven-license-plugin-1.2
# tar cjvf maven-license-plugin-1.2-gentoo.tar.bz2 maven-license-plugin-1.2
SRC_URI="http://gentooexperimental.org/distfiles/${P}-gentoo.tar.bz2"

LICENSE="Apache-2.0"
SLOT="1"
KEYWORDS="~x86"
IUSE=""

DEPEND=">=virtual/jdk-1.4
	dev-java/ant-core"
RDEPEND="${DEPEND}"
S="${WORKDIR}/${P}/license"

src_unpack() {
	unpack ${A}

	cd ${S}
	# This build.xml was generated by 'maven ant', and fixed slightly.
	cp ${FILESDIR}/build-${PV}.xml build.xml

	mkdir -p target/lib
	cd target/lib
	java-pkg_jar-from commons-lang
	java-pkg_jar-from commons-collections
}

src_compile() {
	local antflags="jar -Dnoget=true"
	ant ${antflags} || die "ant failed"
}

src_install() {
	#java-pkg_newjar target/${P}.jar ${PN}.jar
	java-maven_newplugin target/${P}.jar ${PN}.jar
}
