#!/bin/bash
# gcj-jdk installs /usr/bin/gcj-jdk symlink, depending on it would be circular
# so we fallback to gcc-config discovery
GIJ_BIN="/usr/bin/gij"
if [[ ! -f ${GIJ_BIN} ]]; then
	GIJ_BIN="$(gcc-config -B)/gij"
fi
if [[ ! -f ${GIJ_BIN} ]]; then
	echo "gij not found! check that gcc is compiled with gcj flag"
	exit 1
fi
# calling java-config would be an unnecessary slowdown here
${GIJ_BIN} -classpath /usr/share/ecj-gcj/lib/ecj.jar org.eclipse.jdt.internal.compiler.batch.Main "${@}"
