#!/bin/sh

if [ -e /usr/bin/native_gjdoc ]; then
    LD_LIBRARY_PATH=$(gcc-config -L $(ls -1r /etc/env.d/gcc/*4.3.?|head -1)) /usr/bin/native_gjdoc ${1+"$@"};
else
    $(java-config --java) -classpath "$(java-config --classpath=gjdoc,antlr):$CLASSPATH" \
	gnu.classpath.tools.gjdoc.Main ${1+"$@"};
fi
