# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

inherit java-maven

DESCRIPTION="Jar plugin for Maven"
HOMEPAGE="http://maven.apache.org"
# svn co http://svn.apache.org/repos/asf/maven/maven-1/plugins/tags/MAVEN_JAR_1_7/ maven-jar-plugin-1.7
# tar cjvf maven-jar-plugin-1.7-gentoo.tar.bz2 maven-jar-plugin-1.7/
SRC_URI="http://gentooexperimental.org/distfiles/${P}-gentoo.tar.bz2"

LICENSE="Apache-2.0"
SLOT="1"
KEYWORDS="~x86"
IUSE=""

RDEPEND=">=virtual/jdk-1.4
	dev-java/ant-core
	dev-java/velocity
	dev-java/commons-jelly-tags-velocity"
DEPEND="${RDEPEND}"

src_unpack() {
	unpack ${A}

	cd ${S}
	# This build.xml was generated by 'maven ant', and fixed slightly.
	cp ${FILESDIR}/build-${PV}.xml build.xml

	mkdir -p target/lib
	cd target/lib
}

src_compile() {
	local antflags="jar -Dnoget=true"
	ant ${antflags} || die "ant failed"
}

src_install() {
	java-maven_newplugin target/${P}.jar ${PN}.jar
}
