# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

inherit eutils java-pkg-2 java-ant-2

DESCRIPTION="Java Solution for Real-Time and Embedded Systems"
SRC_URI="http://javolution.org/${P}-src.zip"
HOMEPAGE="http://javolution.org"
LICENSE="LGPL-2.1"
SLOT="2.2"
KEYWORDS="~amd64 x86"
IUSE="doc source"

DEPEND=">=virtual/jdk-1.5
	>=dev-java/ant-core-1.4
	app-arch/unzip
	source? ( app-arch/zip )"
RDEPEND=">=virtual/jre-1.5"

S="${WORKDIR}/javolution-${PV%.*}"

src_compile() {
	# their build doesn't create the dir but cannot run with it
	mkdir "${S}/bin"

	# doc is generated by default so we do not specify doc target here
	eant compile jar
}

src_install() {
	java-pkg_dojar "${PN}.jar"
	dodoc doc/coding_standard.txt
	use doc && java-pkg_dojavadoc api
	use doc && dohtml index.html
	use source && java-pkg_dosrc "${S}/src/${PN}"
}
