#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

CRUISE_CONF="/etc/cruisecontrol/config.xml"

CRUISE_HOME="/usr/share/cruisecontrol"

CRUISE_USER="cruise"
CRUISE_GROUP="cruise"

runtime_classpath="$(java-config -p cruisecontrol)"
for package in ${PACKAGE_DEPENDENCIES}; do
	runtime_classpath="${runtime_classpath}:$(java-config -p ${package})"
done

# TODO maybe we could use jsvc from commons-daemon?
JAVA_ARGS="-classpath ${runtime_classpath} \
	-server \
	-Xms128m \
	-Xmx128m \
	-Xss128k \
	-Djavax.management.builder.initial=mx4j.server.MX4JMBeanServerBuilder \
	-Djava.awt.headless=true \
	CruiseControl \
	-configfile ${CRUISE_CONF} \
	-port ${JMX_PORT}"

start() {
	ebegin "Starting CruiseControl"
	start-stop-daemon --start --quiet --chuid ${CRUISE_USER}:${CRUISE_GROUP} --pidfile /var/run/cruisecontrol.pid --background --make-pidfile --chdir /var/cruisecontrol --exec $(java-config --java) -- ${JAVA_ARGS}
	eend $?
}

stop() {
	ebegin "Stopping CruiseControl"
	start-stop-daemon --stop --quiet --pidfile /var/run/cruisecontrol.pid
	eend $?
}

