# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

inherit java-maven

DESCRIPTION="Artifact plugin for Maven"
HOMEPAGE="http://maven.apache.org"
# svn co http://svn.apache.org/repos/asf/maven/maven-1/plugins/tags/MAVEN_ARTIFACT_1_4_1/artifact/ maven-artifact-plugin-1.4.1
# tar cjvf maven-artifact-plugin-1.4.1-gentoo.tar.bz2 maven-artifact-plugin-1.4.1
SRC_URI="http://gentooexperimental.org/distfiles/${P}-gentoo.tar.bz2"


LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~x86"
IUSE=""

DEPEND=">=virtual/jdk-1.4
	dev-java/ant-core"
RDEPEND="${DEPEND}"

src_unpack() {
	unpack ${A}

	cd ${S}
	# This build.xml was generated by 'maven ant', and fixed slightly.
	cp ${FILESDIR}/build-${PV}.xml build.xml

	# update some files to use newer commons-io api
	epatch ${FILESDIR}/${P}-fileutils.patch

	mkdir -p target/lib
	cd target/lib
	java-pkg_jar-from maven-core-1
	java-pkg_jar-from commons-io-1
	java-pkg_jar-from commons-net
	java-pkg_jar-from commons-httpclient
	java-pkg_jar-from commons-lang
	java-pkg_jar-from commons-logging
	java-pkg_jar-from jsch
	java-pkg_jar-from commons-jelly-1
	java-pkg_jar-from commons-jelly-tags-velocity-1
	java-pkg_jar-from velocity
}

src_compile() {
	local antflags="jar -Dnoget=true"
	ant ${antflags} || die "ant failed"
}

src_install() {
	java-maven_newplugin target/${P}.jar ${PN}.jar
}
