.TH eclipse 1 "3.0.0"
.SH "NAME"
.LP 
eclipse \- Eclipse Tools Platform
.SH "SYNTAX"
.LP 
eclipse gensync [\fIplatform options\fP] [\fI-vmargs [Java VM arguments]\fP]

.SH "DESCRIPTION"

\fIeclipse\fR is the Gentoo startup script for the Eclipse Tools platform. It
will search for an appropriate front-end for Eclipse (either gtk+ or Motif, in
order of preference), and start the platform.

.SH "OPTIONS"

.LP
\fB-application <app id>\fB
.IP
Identifies the application to run.  If not specified, the Eclipse workbench is
run.  Applications are declared by plug-ins supplying extensions to the
org.eclipse.core.runtime.applications extension point.


.LP
\fB-boot <boot code path>\fB
.IP
Defines the path to the boot plug-in code (i.e., boot.jar).  Only required when
changing the relative location of startup.jar and boot.jar. 


.LP
\fB-consolelog\fB
.IP
Mirrors the platform's error log to the console used to run Eclipse.


.LP
\fB-data <workspace path>\fB
.IP
Defines the path of the workspace on which to run the platform.


.LP
\fB-debug [options file path]\fB
.IP
Puts the platform in debug mode and loads the debug options in the specified file.  If a file path is not given, the platform looks in the platform install directory and in the workspace's metadata directory for a file called ".options".


.LP
\fB-dev [classpath entries]\fB
.IP
Puts the platform in development mode.  The optional classpath entries (a comma-separated list) are added to each plug-in's classpath.  For example, when developing plug-ins, use "-dev bin" to add the Java tooling's bin directory for each plug-in.  Redundant or non-existant classpath entries are eliminated.


.LP
\fB-nosplash\fB
.IP
Runs the platform without putting up the splash screen.


.LP
\fB-os <os-id>\fB
.IP
Defines the operating system on which the platform is running.  Typically the platform can detect the OS but some situations may require explicit specification.  The value specified here is related to Platform.getOS().


.LP
\fB-vm <vm path>\fB
.IP
Specifies the Java VM to use to run the platform.  If not specified, a Java VM is located relative to the Eclipse executable.


.LP
\fB-ws <ws-id>\fB
.IP
Defines the window system on which the platform is running.  In many cases the platform can detect the window system but some situations may require explicit specification.  The value specified here is related to Platform.getWS().

.SH "SEE ALSO"
.LP 
\fIhttp://dev.gentoo.org/~karltk/projects/eclipse\fR for tips and tricks.

.SH "AUTHORS"
.LP 
Karl Trygve Kalleberg <karltk@gentoo.org>
.br
The Eclipse Project, \fIwww.eclipse.org\fR
