#!/sbin/runscript
# 
# $Header$
# 
# Copyright (C) 2005  Christopher G. Stach II <cgs@ldsys.net>
# 
# Distributed under the terms of the GNU General Public License v2
# 

CRUISE_CONF="/etc/cruisecontrol/config.xml"

CRUISE_HOME="/usr/share/cruisecontrol"

CRUISE_USER="cruise"
CRUISE_GROUP="cruise"

CLASSPATH=${JAVA_HOME}/lib/tools.jar

CLASSPATH="${CLASSPATH}:`java-config -p cruisecontrol`"
CLASSPATH="${CLASSPATH}:`java-config -p log4j`"
CLASSPATH="${CLASSPATH}:`java-config -p jdom-1.0`"
CLASSPATH="${CLASSPATH}:`java-config -p ant-core`"
CLASSPATH="${CLASSPATH}:`java-config -p xerces-1.3`"
CLASSPATH="${CLASSPATH}:`java-config -p xalan`"
CLASSPATH="${CLASSPATH}:`java-config -p jakarta-oro-2.0`"
CLASSPATH="${CLASSPATH}:`java-config -p junit`"
CLASSPATH="${CLASSPATH}:`java-config -p sun-javamail-bin`"
CLASSPATH="${CLASSPATH}:`java-config -p sun-jaf-bin`"
CLASSPATH="${CLASSPATH}:`java-config -p commons-net`"
CLASSPATH="${CLASSPATH}:`java-config -p mx4j-2.1`"

# 
# Need these? -cgs
# 
# $LIBDIR/starteam-sdk.jar
# $LIBDIR/smack.jar

JMX_PORT=8000

JAVA_ARGS="-classpath ${CLASSPATH} \
	-server \
	-Xms128m \
	-Xmx128m \
	-Xss128k \
	-Djavax.management.builder.initial=mx4j.server.MX4JMBeanServerBuilder \
	-Djava.awt.headless=true \
	CruiseControl \
	-configfile ${CRUISE_CONF} \
	-port ${JMX_PORT}"

start() {
	ebegin "Starting CruiseControl"
	start-stop-daemon --start --quiet --chuid ${CRUISE_USER}:${CRUISE_GROUP} --pidfile /var/run/cruisecontrol.pid --background --make-pidfile --chdir /var/cruisecontrol --exec ${JAVA_HOME}/bin/java -- ${JAVA_ARGS}
	eend $?
}

stop() {
	ebegin "Stopping CruiseControl"
	start-stop-daemon --stop --quiet --pidfile /var/run/cruisecontrol.pid
	eend $?
}

