
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

inherit java-pkg

DESCRIPTION="POM plugin for Maven"
HOMEPAGE="http://maven.apache.org"
# svn co http://svn.apache.org/repos/asf/maven/maven-1/plugins/tags/MAVEN_POM_1_5/ maven-pom-plugin-1.5
# tar cjvf maven-pom-plugin-1.5-gentoo.tar.bz2 maven-pom-plugin-1.5/
SRC_URI="http://gentooexperimental.org/distfiles/${P}-gentoo.tar.bz2"

LICENSE="Apache-2.0"
SLOT="1"
KEYWORDS="~x86"
IUSE=""

RDEPEND=">=virtual/jdk-1.4
	dev-java/ant-core"
DEPEND="${RDEPEND}"

src_unpack() {
	unpack ${A}

	cd ${S}
	# This build.xml was generated by 'maven ant', and fixed slightly.
	cp ${FILESDIR}/build-${PV}.xml build.xml

	mkdir -p target/lib
	cd target/lib
	java-pkg_jar-from maven-core-1
	java-pkg_jar-from dom4j-1
	java-pkg_jar-from commons-jelly-tags-log-1
}

src_compile() {
	local antflags="jar -Dnoget=true"
	ant ${antflags} || die "ant failed"
}

src_install() {
	java-pkg_newjar target/${P}.jar ${PN}.jar
}
