.TH "JAVA-PKG.ECLASS" "1" "May 2005" "Portage 2.0.51" "portage"
.SH "DESCRIPTION"
The \fBjava\-pkg\fR eclass contains a suite of functions used in installing
java packages.
.SH "FUNCTIONS"
.TP 
.BR "java-pkg_dosrc " "\fI<directories/files>\fR"
A function to easily package source files to a zip file and install them into
/usr/share/doc/${PF}/source
.SH "REPORTING BUGS"
Please report bugs via http://bugs.gentoo.org/ and assign them to
java@gentoo.org.
.SH "SEE ALSO"
.BR ebuild (5)
.SH "FILES"
.BR /usr/portage/eclass/java\-pkg.eclass
.SH "AUTHORS"
Petteri Räty <betelgeuse>
